on:
  workflow_dispatch:

jobs:
  # build-and-push: 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v5
  #     - name: Login
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ vars.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: BuildAndPush
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         push: true
  #         tags: byasebastien/testcicd
  deploy:
    runs-on: ubuntu-latest
    # needs: build-and-push
    steps:
      - name: Action SSH
        uses: tiyee/action-ssh@v1.0.1
        with:
          host: khunly.be
          port: 22 
          username: debian 
          command: 'echo 42'
          privateKey: ${{ secrets.SSH_KEY }}
